pr:
  branches:
    include:
      - main
  paths:
    include:
      - .azure_pipelines_attestation_container.yml
      - .attestation_container_canary

trigger:
  - main

jobs:
  - template: .azure-pipelines-templates/configure.yml

  - template: .azure-pipelines-templates/deploy_attestation_container.yml
    parameters:
      used_by:
        - test_attestation_container

  - template: .azure-pipelines-templates/test_attestation_container.yml
    parameters:
      job_name: test_attestation_container
      display_name: "Test Attestation Container"
      depends_on: deploy_attestation_container
      run_on: $[ dependencies.deploy_attestation_container.outputs['deploy_attestation_container.ipAddresses'] ]
      host_private_key: $[ dependencies.deploy_attestation_container.outputs['generate_ssh_key.hostPrivKey'] ]
