trigger:
  tags:
    include:
      - ccf-4.*

pr: none

resources:
  containers:
    - container: virtual
      image: ghcr.io/microsoft/ccf/ci/default:build-21-05-2025
      options: --publish-all --cap-add NET_ADMIN --cap-add NET_RAW --cap-add SYS_PTRACE -v /lib/modules:/lib/modules:ro

    - container: snp
      image: ghcr.io/microsoft/ccf/ci/default:build-21-05-2025
      options: --publish-all --cap-add NET_ADMIN --cap-add NET_RAW --cap-add SYS_PTRACE -v /lib/modules:/lib/modules:ro

    - container: sgx
      image: ghcr.io/microsoft/ccf/ci/sgx:build-21-05-2025
      options: --publish-all --cap-add NET_ADMIN --cap-add NET_RAW --device /dev/sgx_enclave:/dev/sgx_enclave --device /dev/sgx_provision:/dev/sgx_provision -v /dev/sgx:/dev/sgx -v /lib/modules:/lib/modules:ro

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/ccf-') }}:
    perf_or_release: release
    perf_tests: no_run
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/ccf-')) }}:
    perf_or_release: perf
    perf_tests: run

jobs:
  - template: .azure-pipelines-templates/configure.yml

  - template: .azure-pipelines-templates/release-matrix.yml
    parameters:
      perf_or_release: ${{ variables['perf_or_release'] }}
      perf_tests: ${{ variables['perf_tests'] }}
