oe_ver: "0.19.13"
# Usually the same, except for rc, where ver is -rc and ver_ is _rc
oe_ver_: "0.19.13"

# Source install
workspace: "/tmp/"
oe_src: "oe-{{ oe_ver }}.tar.gz"
oe_prefix: "/opt/openenclave"
oe_repo: "https://github.com/openenclave/openenclave.git"
oe_playbook: scripts/ansible/oe-contributors-acc-setup-no-driver.yml
oe_build_opts: "-DLVI_MITIGATION=ControlFlow-GNU"

# Binary install
oe_deb: "https://github.com/openenclave/openenclave/releases/download/v{{ oe_ver }}/Ubuntu_2004_open-enclave_{{ oe_ver_ }}_amd64.deb"
oe_host_verify_deb: "https://github.com/openenclave/openenclave/releases/download/v{{ oe_ver }}/Ubuntu_2004_open-enclave-hostverify_{{ oe_ver_ }}_amd64.deb"
