workspace: "/tmp/"
debs:
  - apt-transport-https
  - ninja-build
  - libuv1-dev
  - libc++-10-dev
  - libc++abi-10-dev
  - python3.8-dev
  - python3.8-venv
  - llvm-10
  - clang-10
  - clang-format-10
  - clang-tools-10
  - build-essential
  - expect
  - git
  - ccache
  - kmod # modinfo for sgxinfo.sh
  - cmake
  - libssl-dev
  - jq # operation scripts
  - sudo
  - curl # client test infra
  - shellcheck # bash lint
  - iptables # partition test infra
  - libclang1-9 # required to build doxygen
  - libclang-cpp9 # required to build doxygen
  - pkg-config # required by v8
  - graphviz # required to run doxygen

# Not installed on GitHub Actions environment because of conflicting package
docker_debs:
  - docker-ce-cli

doxygen_ver: "1.9.4"
doxygen_bin: "doxygen-{{ doxygen_ver }}.linux.bin.tar.gz"
doxygen_url: "https://sourceforge.net/projects/doxygen/files/rel-{{ doxygen_ver }}/{{ doxygen_bin }}/download"
