jobs:
  - job: Checks
    displayName: "Release notes check"

    ${{ insert }}: ${{ parameters.env }}

    steps:
      - checkout: self
        clean: true
        fetchDepth: 1

      - script: python3.8 scripts/extract-release-notes.py /dev/null
        displayName: "Check presence of release notes entry"
