steps:
- script: |
    cmake -L .. 2>/dev/null | grep CMAKE_INSTALL_PREFIX: | cut -d = -f 2 > /tmp/install_prefix
    cpack -V -G DEB
    PKG=`ls *.deb`
    cp $PKG $(Build.ArtifactStagingDirectory)
    echo "##vso[task.setvariable variable=pkgname]$PKG"
  workingDirectory: build
  displayName: 'Make .deb package'

- script: |
    sudo apt install ./$(pkgname)
    cat /tmp/install_prefix | xargs ./test_install.sh
  workingDirectory: build
  displayName: Test installed CCF

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)/$(pkgname)
    artifact: $(pkgname)
    displayName: 'Publish CCF Install'