steps:
- script: |
    sudo chmod a+w /opt
    ninja install
    cmake -L .. 2>/dev/null | grep CMAKE_INSTALL_PREFIX: | cut -d = -f 2 > /tmp/install_prefix
  workingDirectory: build
  displayName: 'Install'

- script: |
    INSTALL_PREFIX=`cat /tmp/install_prefix`
    mkdir -p nested/run
    cd nested/run
    python3.7 -m venv env
    source env/bin/activate
    python -m pip install -U -r $INSTALL_PREFIX/bin/requirements.txt
    pip freeze > $INSTALL_PREFIX/bin/requirements.txt
    timeout --signal=SIGINT --kill-after=30s --preserve-status 30s \
      python $INSTALL_PREFIX/bin/start_network.py \
      -p ../../build/liblogging \
      -b $INSTALL_PREFIX/bin \
      -g $(pwd)/../../src/runtime_config/gov.lua \
      -v &
    sleep 20
    python3.7 ../../python/tutorial.py client_info.txt
    cp -r ./workspace/start_network_0/0.ledger .
    cp ./workspace/start_network_0/network_enc_pubk.pem .
    timeout --signal=SIGINT --kill-after=30s --preserve-status 30s \
      python $INSTALL_PREFIX/bin/start_network.py \
      -p ../../build/liblogging \
      -b $INSTALL_PREFIX/bin \
      -v \
      --recover \
      --ledger-dir 0.ledger \
      --network-enc-pubk network_enc_pubk.pem \
      --common-dir ./workspace/start_network_common/
  displayName: Test installed CCF

- script: |
    INSTALL_PREFIX=`cat /tmp/install_prefix`
    cp -r /opt/openenclave $INSTALL_PREFIX
  displayName: Copy OE into install dir

- script: |
    INSTALL_PREFIX=`cat /tmp/install_prefix`
    tar czf $(Build.ArtifactStagingDirectory)/ccf.tar.gz ${INSTALL_PREFIX##/opt/}
  displayName: Create release tarball
  workingDirectory: /opt

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)/ccf.tar.gz
    artifact: ccf.tar.gz
    displayName: 'Publish CCF Install'