steps:
  - script: |
      set -ex
      mkdir ~/.ssh
      echo ${{ parameters.ssh_key }} | base64 -d > ~/.ssh/id_rsa
      # debug
      wc ~/.ssh/id_rsa
      sudo chmod 600 ~/.ssh/id_rsa
      sudo ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      sudo chmod 600 ~/.ssh/id_rsa.pub
    name: setup_key
    displayName: "Install SSH Key from Deployment Step"
