steps:
  - script: |
      set -ex
      cmake -L .. 2>/dev/null | grep CMAKE_INSTALL_PREFIX: | cut -d = -f 2 > /tmp/install_prefix
      cpack -V -G DEB
      INITIAL_PKG=`ls *.deb`
      GITHUB_PKG=${INITIAL_PKG//\~/_}
      mv $INITIAL_PKG $GITHUB_PKG
      cp $GITHUB_PKG $(Build.ArtifactStagingDirectory)
      echo "##vso[task.setvariable variable=pkgname]$GITHUB_PKG"
    workingDirectory: build
    displayName: "Make .deb package"

  - script: |
      set -ex
      python3.8 -m venv env
      source ./env/bin/activate
      pip install -r requirements.txt
      pip install wheel
      python setup.py bdist_wheel
      WHL=`ls dist/*.whl`
      cp $WHL $(Build.ArtifactStagingDirectory)
      WHL=`basename $WHL`
      echo "##vso[task.setvariable variable=wheel]$WHL"
    workingDirectory: python
    displayName: Build wheel

  - script: |
      set -ex
      CCF_VERSION=$(<../../build/VERSION_LONG)
      CCF_VERSION=${CCF_VERSION#ccf-}
      echo "Setting npm package version to ${CCF_VERSION}"
      npm version $CCF_VERSION
      npm pack
      PKG=`ls *.tgz`
      cp $PKG $(Build.ArtifactStagingDirectory)
      echo "##vso[task.setvariable variable=npmtgz]$PKG"
    workingDirectory: js/ccf-app
    displayName: Build npm package

  - script: |
      set -ex
      sudo apt -y install ./$(pkgname)
      cat /tmp/install_prefix | xargs -i bash -c "PYTHON_PACKAGE_PATH=../python ./test_install.sh {} release"
    workingDirectory: build
    displayName: Test installed CCF

  - script: |
      set -ex
      ./tests/test_install_build.sh
    displayName: Test building a sample against installed CCF

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(pkgname)
      artifact: $(pkgname)
      displayName: "Publish CCF Debian Package"

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(wheel)
      artifact: $(wheel)
      displayName: "Publish CCF Wheel"

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(npmtgz)
      artifact: $(npmtgz)
      displayName: "Publish CCF NPM Package"
