
steps:
- script: |
    tar -cavf artifact.tar.gz `find . -maxdepth 1 -type f`
  displayName: Compress build artifact
  workingDirectory: build

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: ${{ parameters.artifact_name }}
    targetPath: build/artifact.tar.gz
