- name: Include vars
  include_vars: common.yml

- name: Download CCF release
  get_url:
    url: "{{ ccf_url }}"
    dest: "{{ workspace }}"

- name: Create directory
  file:
    path: "/opt/ccf"
    state: directory
  become: true

- name: Expand CCF release
  unarchive:
    src: "/tmp/{{ ccf_tarball }}"
    dest: "/opt/ccf"
    extra_opts:
      - --strip-components=1
  become: true

- name: Copy cchost
  copy:
    src: "/opt/ccf/bin/cchost"
    dest: "/usr/bin/cchost"
    remote_src: true
    mode: a=rx
  become: true
  when: run_only|bool

- name: Remove release
  file:
    path: "/opt/ccf"
    state: absent
  become: true
  when: run_only|bool
