name: "Backport PR to LTS release branch(es)"

on:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
      - closed

permissions: read-all

jobs:
  backport:
    name: Backport PR
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'auto-backport')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # This is necessary as the repository is checked out to avoid merge conflicts
      # on daily canary file
      - name: Sets committer to GitHub Actions bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Local canary file always wins
        run: |
          git config --local include.path .gitconfig
          git config --global merge.keeplocal.name "Always keep local file during merge"
          git config --global merge.keeplocal.driver true

      # Update backport action (https://github.com/sqren/backport/issues/391#issuecomment-1156355381)
      - name: Backport Action
        uses: sorenlouv/backport-github-action@main
        with:
          github_token: ${{ secrets.BACKPORT_ACTION }}
