name: "Daily Build Status"

on: [push, pull_request]

jobs:
  daily:
    name: Check Daily Build status
    runs-on: ubuntu-latest

    steps:
      - run: |
          curl -s https://dev.azure.com/MSRC-CCF/CCF/_apis/build/status/CCF%20GitHub%20Daily?branchName=main | grep succeeded
